### PR TITLE
lib: Replace `mkdirp-then` with `mkdirp`

### LINKED ISSUE #59: replace `mkdirp-then` with `fs.mkdirSync`
[this](https://github.com/duojs/package/blob/0.8.0/lib/index.js#L55) can throw an uncatchable exception after the first tick.  any reason we're not just doing `fs.mkdirSync(...)`?

### PR DESCRIPTION
**Pull request by stephenmathieson**
Using `mkdirp-then` will allow an exception to be thrown after the
first tick.  If an error occurs, throwing it synchronously will prevent
applications from crashing after they've properly booted.

Closes #59.

### CODE REVIEW

**Comment by matthewmueller** [comment]
@dominicbarnes i think you changed this. what was the reason again?

**Comment by dominicbarnes** [comment]
The idea here was to eliminate anything synchronous, which I still want to do. I think I actually made the previous change incorrectly though, I should have basically added a `yield mkdir(cachepath);` before attempting to write to the cache. 

Doing it properly would remove the sync call as well as leaving a clear place for an Error to be thrown that duo can catch, would you be open to me submitting another PR on this @stephenmathieson ?

**Comment by stephenmathieson** [comment]
Nope, wouldn't mind. Just don't want apps to crash after the first tick ;)

**Comment by dominicbarnes** [comment]
Yeah, that's definitely not good. I will make sure that doesn't happen :)

**Pull request merged**
